# Generated by Django 5.2 on 2025-05-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('wheelchair_entrance', models.BooleanField(null=True)),
                ('wheelchair_restroom', models.BooleanField(null=True)),
                ('wheelchair_parking', models.BooleanField(null=True)),
                ('wheelchair_seating', models.BooleanField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('cities', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transportation', models.JSONField(default=list)),
                ('max_distance', models.IntegerField(default=0)),
                ('interests', models.JSONField(default=list)),
                ('mood', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_places', models.ManyToManyField(blank=True, help_text='사용자가 여행에 포함하기로 선택한 장소(Place 객체 참조)', related_name='requested_by', to='main.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.travelrequest')),
            ],
            options={
                'unique_together': {('travel_request', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('transport_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='main.place')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.travelschedule')),
            ],
        ),
    ]
