# Generated by Django 5.2 on 2025-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='wheelchair_parking',
        ),
        migrations.RemoveField(
            model_name='place',
            name='wheelchair_restroom',
        ),
        migrations.RemoveField(
            model_name='place',
            name='wheelchair_seating',
        ),
    ]
