# Generated by Django 5.2 on 2025-05-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_place_wheelchair_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='lng',
        ),
    ]
