# Generated by Django 5.2 on 2025-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_scheduleitem_address_remove_scheduleitem_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='user',
        ),
    ]
